### ISSUE TITLE
Missing hyperopt import

### ISSUE THREAD

**Issue by bstuddard** [databricks/automl#40] opened 2022-04-06 16:51 UTC
I'm getting an import error "cannot import name 'FMIN_CANCELLED_REASON_EARLY_STOPPING' from 'hyperopt.spark'". This occurred through databricks UI and automl api using runtimes 10.3 ML and 10.4 ML. 

Any ideas on how to get past this? It seems to happen on import...from databricks.automl.supervised_learner import SupervisedLearner.

**Comment by Loquats** [comment] 2022-04-07 00:14
Hi @bstuddard. I haven't been able to reproduce your issue. I ran these imports on a 10.4 ML cluster, and they worked fine:
```
from databricks.automl.supervised_learner import SupervisedLearner
from hyperopt.spark import FMIN_CANCELLED_REASON_EARLY_STOPPING
```
Could you check if your cluster has the correct version of hyperopt installed?
```
import hyperopt
hyperopt.__version__
```
This should return `0.2.7+db1`. Perhaps your cluster has some packages installed that changed the version of hyperopt.

**Comment by Loquats** [comment] 2022-04-07 20:45
Yes, that's the cause. The `+db` version indicates that the hyperopt package installed on ML Runtime by default contains some features that exist on Databricks, but not in open source hyperopt. `FMIN_CANCELLED_REASON_EARLY_STOPPING` is an example of that.

This probably happened because hyperopt was reinstalled, or packages that depend on hyperopt were modified. Could you check if there were package modifications, eg. in your notebook using `%pip` or in the cluster libraries UI? Databricks recommends not modifying python packages on the cluster you use to run automl, [per requirements](https://docs.databricks.com/applications/machine-learning/automl.html#requirements), to avoid this issue.

**Comment by bstuddard** [comment] 2022-04-07 21:10
> Yes, that's the cause. The `+db` version indicates that the hyperopt package installed on ML Runtime by default contains some features that exist on Databricks, but not in open source hyperopt. `FMIN_CANCELLED_REASON_EARLY_STOPPING` is an example of that.
> 
> This probably happened because hyperopt was reinstalled, or packages that depend on hyperopt were modified. Could you check if there were package modifications, eg. in your notebook using `%pip` or in the cluster libraries UI? Databricks recommends not modifying python packages on the cluster you use to run automl, [per requirements](https://docs.databricks.com/applications/machine-learning/automl.html#requirements), to avoid this issue.

That was it, thanks! I verified on a cluster without any other library dependencies, outside of the runtime pre-installed ones, and was able to get it working.

**Comment by Loquats** [comment] 2022-04-08 04:58
Glad it's working now! I'll close this ticket.

**Closed by Loquats** 2022-04-08 04:58 UTC
